# Composite action to set up the CI environment
#
# Installs uv, syncs Python dependencies, and optionally installs:
# - Podman (for container operations)
# - Node.js (for JS tooling)
# - Devcontainer CLI + docker-compose wrapper (for integration tests)
#
# Inputs:
#   install-podman:           Install podman (default: false)
#   install-node:             Install Node.js (default: false)
#   node-version:             Node.js version (default: '20')
#   install-devcontainer-cli: Install devcontainer CLI + docker-compose wrapper (default: false)
#
# Outputs:
#   uv-version: The version of uv that was installed
#
# Usage:
#   # Minimal (uv + Python + project dependencies)
#   - uses: ./.github/actions/setup-env
#
#   # Image tests (add podman)
#   - uses: ./.github/actions/setup-env
#     with:
#       install-podman: 'true'
#
#   # Integration tests (full stack)
#   - uses: ./.github/actions/setup-env
#     with:
#       install-podman: 'true'
#       install-devcontainer-cli: 'true'

name: 'Setup Environment'
description: 'Set up CI environment with uv, Python deps, and optional tools (podman, Node.js, devcontainer CLI)'

inputs:
  install-podman:
    description: 'Install podman for container operations'
    required: false
    default: 'false'
  install-node:
    description: 'Install Node.js'
    required: false
    default: 'false'
  node-version:
    description: 'Node.js version (when install-node is true)'
    required: false
    default: '20'
  install-devcontainer-cli:
    description: 'Install @devcontainers/cli and docker-compose wrapper (requires Node.js)'
    required: false
    default: 'false'
  install-just:
    description: 'Install just command runner for Justfile support'
    required: false
    default: 'true'

outputs:
  uv-version:
    description: 'Version of uv installed'
    value: ${{ steps.setup-uv.outputs.uv-version }}

runs:
  using: composite
  steps:
    # ── Code checkout ───────────────────────────────────────────────────
    - name: Checkout code
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4

    # ── Python ───────────────────────────────────────────────────────────
    - name: "Set up Python"
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6
      with:
        python-version-file: "pyproject.toml"

    # ── uv ─────────────────────────────────────────────────────────────
    - name: Install uv
      id: setup-uv
      uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b  # v7
      with:
        enable-cache: true
        # Install a specific version of uv.
        version: "0.10.0"

    # ── Python dependencies ───────────────────────────────────────────────
    - name: Sync Python dependencies
      shell: bash
      run: uv sync --frozen --all-extras

    # ── Podman ──────────────────────────────────────────────────────────
    - name: Install podman
      if: inputs.install-podman == 'true'
      shell: bash
      run: |
        set -euo pipefail
        if ! command -v podman &> /dev/null; then
          echo "Installing podman..."
          sudo apt-get update -qq
          sudo apt-get install -y podman
        fi
        echo "podman $(podman --version)"

    # ── Node.js ─────────────────────────────────────────────────────────
    # Also installed when install-devcontainer-cli is true (npm is required)
    - name: Install Node.js
      if: inputs.install-node == 'true' || inputs.install-devcontainer-cli == 'true'
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4
      with:
        node-version: ${{ inputs.node-version }}

    # ── Just (task runner) ──────────────────────────────────────────────
    - name: Install just
      uses: taiki-e/install-action@3035223527de4d6eb6207d7b9f901df966359a8e  # just
      with:
        tool: just

    # ── Devcontainer CLI + docker-compose wrapper ───────────────────────
    # Requires Node.js (automatically installed above when this flag is set)
    - name: Install devcontainer CLI
      if: inputs.install-devcontainer-cli == 'true'
      shell: bash
      run: |
        set -euo pipefail

        # Create docker-compose wrapper (devcontainer CLI needs standalone docker-compose;
        # the runner only has 'docker compose' v2 plugin, not the standalone binary)
        printf '#!/bin/sh\nexec docker compose "$@"\n' | sudo tee /usr/local/bin/docker-compose > /dev/null
        sudo chmod +x /usr/local/bin/docker-compose
        echo "docker-compose wrapper: $(docker-compose version --short)"

        # Install devcontainer CLI
        echo "Installing @devcontainers/cli..."
        npm install -g @devcontainers/cli@0.81.1
        echo "devcontainer $(devcontainer --version)"
