# requirements.yaml
# Single source of truth for development dependencies
# Used by: init.sh (installation), docs/generate.py (documentation)
#
# Schema:
#   name: Display name for the dependency
#   version: Version constraint (for display)
#   purpose: Brief description of why it's needed
#   required: Whether the dependency is mandatory (default: true)
#   check:
#     command: Command to check if installed (returns 0 if installed)
#     version_command: Command to get version string (optional)
#     version_regex: Regex to extract version from version_command output (optional)
#   install:
#     macos: Homebrew command or instructions
#     debian: apt command or instructions
#     fedora: dnf command or instructions (optional)
#     alpine: apk command or instructions (optional)
#     manual: Manual installation instructions (fallback)

dependencies:
  # Container Runtime (required)
  - name: podman
    version: ">=4.0"
    purpose: Container runtime, compose, and image building
    required: true
    check:
      command: command -v podman
      version_command: podman --version
      version_regex: 'podman version (\d+\.\d+)'
    install:
      macos: brew install podman
      debian: sudo apt install -y podman
      fedora: sudo dnf install -y podman
      manual: https://podman.io/getting-started/installation

  # Build Automation
  - name: just
    version: ">=1.40.0"
    purpose: Command runner for task automation
    required: true
    check:
      command: command -v just
      version_command: just --version
      version_regex: 'just (\d+\.\d+)'
    install:
      macos: brew install just
      debian: |
        curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin
      fedora: sudo dnf install -y just
      manual: https://github.com/casey/just#installation

  # Version Control
  - name: git
    version: ">=2.34"
    purpose: Version control and pre-commit hooks
    required: true
    check:
      command: command -v git
      version_command: git --version
      version_regex: 'git version (\d+\.\d+)'
    install:
      macos: brew install git
      debian: sudo apt install -y git
      fedora: sudo dnf install -y git
      manual: https://git-scm.com/downloads

  # SSH (for authentication)
  - name: ssh
    version: latest
    purpose: GitHub authentication and commit signing
    required: true
    check:
      command: command -v ssh
      version_command: ssh -V 2>&1
      version_regex: 'OpenSSH_(\d+\.\d+)'
    install:
      macos: brew install openssh
      debian: sudo apt install -y openssh-client
      fedora: sudo dnf install -y openssh-clients
      manual: Usually pre-installed on Unix systems

  # GitHub CLI
  - name: gh
    version: latest
    purpose: GitHub CLI for repository and PR/issue management
    required: true
    check:
      command: command -v gh
      version_command: gh --version
      version_regex: 'gh version (\d+\.\d+)'
    install:
      macos: brew install gh
      debian: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update && sudo apt install -y gh
      fedora: sudo dnf install -y gh
      manual: https://cli.github.com/

  # Node.js (for devcontainer CLI)
  - name: npm
    version: latest
    purpose: Node.js package manager (for DevContainer CLI)
    required: true
    check:
      command: command -v npm
      version_command: npm --version
      version_regex: '(\d+\.\d+)'
    install:
      macos: brew install node
      debian: sudo apt install -y nodejs npm
      fedora: sudo dnf install -y nodejs npm
      manual: https://nodejs.org/

  # Python tooling (auto-installed by setup.sh)
  - name: uv
    version: ">=0.8"
    purpose: Python package and project manager
    required: true
    check:
      command: command -v uv
      version_command: uv --version
      version_regex: 'uv (\d+\.\d+)'
    install:
      all: curl -LsSf https://astral.sh/uv/install.sh | sh
      manual: https://github.com/astral-sh/uv

  # DevContainer CLI (auto-installed by setup.sh)
  - name: devcontainer
    version: "0.81.1"
    purpose: DevContainer CLI for testing devcontainer functionality
    required: true
    check:
      command: command -v devcontainer
      version_command: devcontainer --version
      version_regex: '(\d+\.\d+\.\d+)'
    install:
      all: npm install -g @devcontainers/cli@{{version}}
      manual: https://github.com/devcontainers/cli

# Optional dependencies for multi-arch builds
optional:
  - name: qemu-user-static
    version: latest
    purpose: Multi-architecture container builds (AMD64/ARM64)
    required: false
    check:
      command: test -f /proc/sys/fs/binfmt_misc/qemu-aarch64
    install:
      debian: |
        sudo apt install -y qemu-user-static
        sudo podman run --privileged --rm docker.io/tonistiigi/binfmt --install all
      fedora: |
        sudo dnf install -y qemu-user-static
        sudo podman run --privileged --rm docker.io/tonistiigi/binfmt --install all
      manual: Only needed for cross-architecture builds
