# Composite action to set up Python environment with uv package manager
#
# This action installs uv and sets up Python dependencies using uv sync.
# It's designed to be reused across multiple workflows in this repository.
#
# Inputs:
#   sync-groups: Optional dependency groups to sync (default: 'test')
#                Multiple groups can be specified separated by commas
#                Examples: 'test', 'test,dev', 'test,lint'
#
# Outputs:
#   uv-version: The version of uv that was installed
#
# Usage:
#   - uses: ./.github/actions/setup-python-uv
#     with:
#       sync-groups: 'test,dev'

name: 'Setup Python with uv'
description: 'Install uv and sync Python dependencies'

inputs:
  sync-groups:
    description: 'Dependency groups to sync (comma-separated, e.g., test,dev)'
    required: false
    default: 'test'

outputs:
  uv-version:
    description: 'Version of uv installed'
    value: ${{ steps.install-uv.outputs.version }}

runs:
  using: composite
  steps:
    - name: Install uv
      id: install-uv
      shell: bash
      run: |
        set -euo pipefail

        if ! command -v uv &> /dev/null; then
          echo "Installing uv..."

          # Retry logic for curl download (network flakiness)
          RETRIES=3
          for i in $(seq 1 $RETRIES); do
            if curl -LsSf https://astral.sh/uv/install.sh | sh; then
              echo "Installation successful"
              break
            else
              if [ $i -lt $RETRIES ]; then
                echo "Installation failed, retrying ($i/$RETRIES)..."
                sleep 2
              else
                echo "Installation failed after $RETRIES attempts"
                exit 1
              fi
            fi
          done

          # Add to PATH for subsequent steps
          export PATH="$HOME/.cargo/bin:$PATH"
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        else
          echo "uv already installed"
        fi

        # Output version
        UV_VERSION=$(uv --version | cut -d' ' -f2)
        echo "version=$UV_VERSION" >> $GITHUB_OUTPUT
        echo "uv version: $UV_VERSION"

    - name: Sync Python dependencies
      shell: bash
      run: |
        set -euo pipefail

        # Parse sync-groups input and build uv sync command
        SYNC_GROUPS="${{ inputs.sync-groups }}"

        if [ -z "$SYNC_GROUPS" ]; then
          SYNC_CMD="uv sync"
        else
          # Split by comma and build --group flags
          IFS=',' read -ra GROUPS <<< "$SYNC_GROUPS"
          SYNC_CMD="uv sync"
          for group in "${GROUPS[@]}"; do
            # Trim whitespace
            group=$(echo "$group" | xargs)
            SYNC_CMD="$SYNC_CMD --group $group"
          done
        fi

        # Retry logic for uv sync (network flakiness when downloading packages)
        echo "Running: $SYNC_CMD"
        RETRIES=3
        for i in $(seq 1 $RETRIES); do
          if eval "$SYNC_CMD"; then
            echo "Dependencies synced successfully"
            break
          else
            if [ $i -lt $RETRIES ]; then
              echo "Sync failed, retrying ($i/$RETRIES)..."
              sleep 2
            else
              echo "Sync failed after $RETRIES attempts"
              exit 1
            fi
          fi
        done

    - name: Verify Python environment
      shell: bash
      run: |
        set -euo pipefail
        echo "Verifying Python environment..."
        uv run python --version
        echo "Python environment ready"
